### ISSUE TITLE
iOS - Splash Screen

### ISSUE THREAD

**Issue by lawtonj404** [SuperPWA/Super-Progressive-Web-Apps#175]
It was announced that 2.1.7 introduced splash screen support for all iOS device sizes.

Following a number of hours testing and changing versions on our development site we believe this function does not work as intended and fails to show any splash screen on multiple device sizes.

Tested on multiple websites on various hosting platforms: 34SP, GoDaddy, TSO, Microsoft Azure, Krystal etc

Test Hardware: (Latest Stable iOS Version)

iPhone X
iPad Pro 12
iPhone XS Max
iPhone 12 Pro
iPhone 12
iPad Mini
iPad 9.7”

Was this announced but not functional on release or is there an ongoing bug that still needs to be resolved.

I can see it works correctly on the product website but not on the latest plug-in since addition of feature in version 2.1.7

Any help is appreciated

**Comment by syedimran22** [comment]
Released in version : 2.1.10

**Comment by lawtonj404** [comment]
![CD78D933-9060-4866-ABE7-B4AEA9F7049D](https://user-images.githubusercontent.com/26346605/117656255-0c051a00-b190-11eb-9396-283118ae1a53.png)

**Comment by lawtonj404** [comment]
> Released in version : 2.1.10

Still not working, tested on multiple hosts and sites.

**Comment by syedimran22** [comment]
@lawtonj404  Sorry for the inconvenience you are facing could you share your site URL where SuperPWA is install I will look into it.

**Comment by lawtonj404** [comment]
First site you can test is support.hixongroup.com , please note we have removed all plugins and tested, same result, the load image does not work.


Kind Regards,
Jonathan Lawton
Managing Director | Hixon Group Limited
Business IT Support & Cloud Solutions Specialists.
Tel:  01782 365124
Email:  ***@***.***
Web:  www.hixongroup.com
Microsoft Partner: Cloud Solutions Provider (CSP)
​Please note: We accept no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing. ​Hixon Group Limited is Registered in England and Wales: 07658475, Registered Office: Unit 3 Carlton House, Registry Street, Stoke-on-Trent, ST4 1JP.

**Comment by lawtonj404** [comment]
yeah, no problem.

https://support.hixongroup.com

**Comment by supernation** [comment]
-- Please reply above this line --


            Hi Admin,

Thank you for reaching out to us.

Could you please let us know, is your iOS splash screen issue is
resolved? as you raised a ticket on GitHub regarding this issue.
GitHub Ticket URL:
https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/175#issuecomment-874309332
[1]

Looking forward to hearing from you soon.
Have a great day...:)

Links:
------
[1]
https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/175#issuecomment-874309332

Regards,
Mohammed Qutubuddin Nasir
Magazine3.in Support Team 

How would you rate my reply?
Great [1]    Okay [2]    Not Good [3]


Links:
------
[1]
https://secure.helpscout.net/satisfaction/438901509/record/4546493036/1/
[2]
https://secure.helpscout.net/satisfaction/438901509/record/4546493036/2/
[3]
https://secure.helpscout.net/satisfaction/438901509/record/4546493036/3/

**Comment by syedimran22** [comment]
This issue is still in debugging mode once the issue is found we can reopen this ticket
